name: Workflow for master branch

on:
  push:
    branches: [ master ]

jobs:
  

  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g https://apigcp.nimbella.io/downloads/nim/nimbella-cli.tgz
    - run: npm ci
    - run: npm run ci:deploy

    env:
      DEPLOYER_LOGIN_TOKEN: ${{ secrets.DEPLOYER_LOGIN_TOKEN }}
